# Use the official Python image as the base image
FROM python:3.9-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Copy the requirements file into the container and install the dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy the source code into the container
COPY . .

# # Expose port 5332
# EXPOSE 5332

# Start the Python application
CMD ["python", "main.py"]